// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ4lHFOsHxaIjvPgYYVGnraO_56jqgHrQ',
    appId: '1:647999985726:web:7013f3b3e739b46a13596f',
    messagingSenderId: '647999985726',
    projectId: 'prescription-458715',
    authDomain: 'prescription-458715.firebaseapp.com',
    storageBucket: 'prescription-458715.firebasestorage.app',
    measurementId: 'G-9G7JDJXPJC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd2IIcAWqvRkH7XO3U91KlGV1IQsj7BJk',
    appId: '1:647999985726:android:4d0db53a21e9e0f513596f',
    messagingSenderId: '647999985726',
    projectId: 'prescription-458715',
    storageBucket: 'prescription-458715.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwmjJfY57pmW5g3GCJHoGENhErg3J1PDg',
    appId: '1:647999985726:ios:3eb60681c893d4b713596f',
    messagingSenderId: '647999985726',
    projectId: 'prescription-458715',
    storageBucket: 'prescription-458715.firebasestorage.app',
    androidClientId:
        '647999985726-7hsvs94nut5mnr70j68dfst7d3ghckf3.apps.googleusercontent.com',
    iosClientId:
        '647999985726-6a0hkr6j1frc7q6ihnra24ukbob77ft2.apps.googleusercontent.com',
    iosBundleId: 'com.example.prescriptionreader',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwmjJfY57pmW5g3GCJHoGENhErg3J1PDg',
    appId: '1:647999985726:ios:3eb60681c893d4b713596f',
    messagingSenderId: '647999985726',
    projectId: 'prescription-458715',
    storageBucket: 'prescription-458715.firebasestorage.app',
    androidClientId:
        '647999985726-7hsvs94nut5mnr70j68dfst7d3ghckf3.apps.googleusercontent.com',
    iosClientId:
        '647999985726-6a0hkr6j1frc7q6ihnra24ukbob77ft2.apps.googleusercontent.com',
    iosBundleId: 'com.example.prescriptionreader',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZ4lHFOsHxaIjvPgYYVGnraO_56jqgHrQ',
    appId: '1:647999985726:web:325d78b535595bc313596f',
    messagingSenderId: '647999985726',
    projectId: 'prescription-458715',
    authDomain: 'prescription-458715.firebaseapp.com',
    storageBucket: 'prescription-458715.firebasestorage.app',
    measurementId: 'G-ER7FZ3Z3ED',
  );
}
